TestSuite[{
	"normalizeOptionName.mt",
	"normalizeOptionNamePattern.mt",
	"allTrue.mt",
	"chooseOptionDuplicates.mt",
	"generateValidator.mt"
	,
	"CheckOption.mt",
	"CheckOptionRelations.mt",
	"ValidOptionsQ.mt",
	"ValidOptionsPattern.mt",
	"QuietValidOptionsPattern.mt",
	"InvalidOptionsPattern.mt",
	"SetDefaultOptionsValidation.mt",
	"CheckedOptionValue.mt",
	"WithOptionValueChecks.mt"
	,
	"Examples/evaluateBodyRuntime.mt",
	"Examples/evaluatePattSubOpt.mt",
	"Examples/unevaluatedExclusiveHeld.mt",
	"Examples/unevaluatedNonExclusive.mt"
}]